# SA1 ------ + ----- SA2 ------- + ------ SA3W ------- + ----- SA4
#                                                      + ----- WV2
#        Hp0 <-5cm--
version: 1
tracks:
  - id: SA1
    # In mm.
    length: 100
    #type: regular
    occupancy_id: 1
  - id: SA2
    length: 800
    occupancy_id: 2
  - id: SA3W
    length: 100
    type: turnout
    occupancy_id: 3
    throw_id: 4
    reverse_polarity_id: 5
  - id: SA4
    length: 150
    occupancy_id: 6
  - id: WV2
    length: 40
    occupancy_id: 7
connections:
  # Having only one connection indicates one terminating end.
  SA1:
    - to: SA2
      # This connection is on the opposite track compared to the regular one which increases its cost.
      opposite_direction: true
  # Modeling the connection both ways SA1 <-> SA2 means the train can move both ways.
  SA2:
    - to: SA1
    - to: SA3W
      opposite_direction: true
  # Having more than two connections indicates a turnout.
  SA3W:
    - to: SA2
    - to: SA4
      # Indicate this connection is from a turnout branch.
      branch: true
      opposite_direction: true
    - to: WV2
      branch: true
  SA4:
    - to: SA3W
  WV2:
    - to: SA3W
signals:
  - id: S1
    from: SA2
    to: SA1
    type: main
    # Distance "from" SA2 until the signal.
    # In mm.
    distance: 50
    aspects:
      - name: Hp 0
